### ISSUE TITLE
Inheritance

### ISSUE THREAD

**Issue by simplifiedotnet** [kylekatarnls/ci-jade#1]
Hi, does this engine support inheritance? A doc would also be nice. Please see http://jade-lang.com/reference/inheritance

**Comment by kylekatarnls** [comment]
Yes, it is supported. ci-jade is [jade-php](https://github.com/kylekatarnls/jade-php) for CodeIgniter. See the [readme](https://github.com/kylekatarnls/ci-jade/blob/master/README.md) for the install, then the [jade lang doc](http://jade-lang.com/) for the use.
